/// Référentiel des 13 personnalités testées : parti, bloc politique et
/// ordre de présentation retenu par Ipsos (de la gauche vers la droite).
table Candidats
	lineageTag: 9a67dae1-f9bc-4c91-9a7d-165c93657eee

	/// Nom de la personnalité testée.
	column Candidat
		dataType: string
		lineageTag: fe06ca38-d703-4956-9905-7ecab2ff1d72
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: Candidat

		annotation SummarizationSetBy = User

	/// Nom de famille seul, pour les axes de graphiques étroits.
	column 'Nom court'
		dataType: string
		lineageTag: 1e49f8c5-2383-4113-8643-704d8d43ac60
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: NomCourt

		annotation SummarizationSetBy = User

	/// Formation politique de rattachement.
	column Parti
		dataType: string
		lineageTag: dee84c6a-8fdc-4b6a-8ea7-57aab82aba68
		summarizeBy: none
		sourceColumn: Parti

		annotation SummarizationSetBy = User

	/// Regroupement analytique en cinq blocs politiques.
	column Bloc
		dataType: string
		lineageTag: ebb894e4-67e9-4504-aa58-08dcb5af0146
		summarizeBy: none
		sortByColumn: OrdreBloc
		sourceColumn: Bloc

		annotation SummarizationSetBy = User

	column OrdreBloc
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1bb7836e-f584-42b5-9d87-1d93d584f952
		summarizeBy: none
		sourceColumn: OrdreBloc

		annotation SummarizationSetBy = User

	column Ordre
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aa166819-fefb-4756-8043-05a87ce62c8d
		summarizeBy: none
		sourceColumn: Ordre

		annotation SummarizationSetBy = User

	/// Code couleur du parti, utilisable en mise en forme conditionnelle.
	column Couleur
		dataType: string
		isHidden
		lineageTag: 2ce33afc-f118-403e-9dfe-2e45ab8a45e1
		summarizeBy: none
		sourceColumn: Couleur

		annotation SummarizationSetBy = User

	/// Code couleur du bloc politique d'appartenance.
	column CouleurBloc
		dataType: string
		isHidden
		lineageTag: 43747e78-1380-4cb2-8036-5b769b4bb0b5
		summarizeBy: none
		sourceColumn: CouleurBloc

		annotation SummarizationSetBy = User

	partition Candidats = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "Candidats.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"Candidat", type text}, {"NomCourt", type text}, {"Parti", type text}, {"Bloc", type text}, {"OrdreBloc", Int64.Type}, {"Ordre", Int64.Type}, {"Couleur", type text}, {"CouleurBloc", type text}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
