/// Référentiel des 13 personnalités testées : parti, bloc politique et
/// ordre de présentation retenu par Ipsos (de la gauche vers la droite).
table Candidats
	lineageTag: 703b5330-91b8-424b-b063-10d66c9bb949

	/// Nom de la personnalité testée.
	column Candidat
		dataType: string
		lineageTag: 3af7bf1c-b895-4b72-a173-299721b6dafc
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: Candidat

		annotation SummarizationSetBy = User

	/// Nom de famille seul, pour les axes de graphiques étroits.
	column NomCourt
		dataType: string
		lineageTag: 7094eb01-b3c4-47d4-94ce-65414f08c05d
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: NomCourt

		annotation SummarizationSetBy = User

	/// Formation politique de rattachement.
	column Parti
		dataType: string
		lineageTag: c442ae92-ee71-454e-a570-7a19c065ae0a
		summarizeBy: none
		sourceColumn: Parti

		annotation SummarizationSetBy = User

	/// Regroupement analytique en cinq blocs politiques.
	column Bloc
		dataType: string
		lineageTag: cc7f7324-7f59-4a71-9dd5-1b872720204d
		summarizeBy: none
		sortByColumn: OrdreBloc
		sourceColumn: Bloc

		annotation SummarizationSetBy = User

	column OrdreBloc
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: beb1e3c2-f509-4dce-b942-477f0d108ed7
		summarizeBy: none
		sourceColumn: OrdreBloc

		annotation SummarizationSetBy = User

	column Ordre
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 547b2ba1-c7ef-46b2-912c-abe9881a4ff6
		summarizeBy: none
		sourceColumn: Ordre

		annotation SummarizationSetBy = User

	/// Code couleur du parti, utilisable en mise en forme conditionnelle.
	column Couleur
		dataType: string
		isHidden
		lineageTag: 7e41ec36-f853-4935-aea0-0c7a522f5c8d
		summarizeBy: none
		sourceColumn: Couleur

		annotation SummarizationSetBy = User

	/// Code couleur du bloc politique d'appartenance.
	column CouleurBloc
		dataType: string
		isHidden
		lineageTag: 82d13790-7ff6-42ba-96a4-ea357647d463
		summarizeBy: none
		sourceColumn: CouleurBloc

		annotation SummarizationSetBy = User

	partition Candidats = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "Candidats.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"Candidat", type text}, {"NomCourt", type text}, {"Parti", type text}, {"Bloc", type text}, {"OrdreBloc", Int64.Type}, {"Ordre", Int64.Type}, {"Couleur", type text}, {"CouleurBloc", type text}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
