/// Les 8 hypothèses de premier tour testées dans l'enquête. Chaque hypothèse
/// a sa propre base de répondants (personnes certaines d'aller voter et ayant
/// exprimé une intention) et son propre taux de non-réponse.
table Hypotheses
	lineageTag: bfaf260b-7d53-43a0-bd98-1a7097e2243d

	/// Identifiant court de l'hypothèse (H1 à H8).
	column Code
		dataType: string
		lineageTag: 3990fec7-3809-486c-a8ac-9f73def3137e
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: Code

		annotation SummarizationSetBy = User

	/// Libellé court : les grands candidats de l'hypothèse.
	column 'Hypothèse'
		dataType: string
		lineageTag: 7b221b52-a09c-4662-aa95-374b4240e839
		summarizeBy: none
		sortByColumn: Ordre
		sourceColumn: Hypothese

		annotation SummarizationSetBy = User

	/// Intitulé complet tel qu'imprimé dans le rapport Ipsos.
	column 'Intitulé'
		dataType: string
		lineageTag: 9b6fdcd8-6cd5-49c7-9afd-3faf3c3c230c
		summarizeBy: none
		sourceColumn: Intitule

		annotation SummarizationSetBy = User

	/// Nombre de personnes exprimant une intention de vote.
	column 'Base exprimée'
		dataType: int64
		formatString: #,0
		lineageTag: 610e276c-f02c-4706-81c5-0a450b51455a
		summarizeBy: none
		sourceColumn: Base

		annotation SummarizationSetBy = User

	/// Part des personnes certaines d'aller voter sans intention exprimée.
	column 'Sans réponse (%)'
		dataType: double
		formatString: 0.0
		lineageTag: 9eb598f3-9ac1-4282-80f7-6d5af534ac99
		summarizeBy: none
		sourceColumn: SansReponse

		annotation SummarizationSetBy = User

	/// Nombre de candidats présents dans l'hypothèse.
	column 'Nb candidats'
		dataType: int64
		formatString: 0
		lineageTag: f8bab7ba-de2f-4611-9dfc-680def4e38ed
		summarizeBy: none
		sourceColumn: NbCandidats

		annotation SummarizationSetBy = User

	/// Candidat du Rassemblement national testé.
	column 'Finaliste RN'
		dataType: string
		lineageTag: ee1bd637-76a2-4de2-af0f-bf9f9306cb24
		summarizeBy: none
		sourceColumn: FinalisteRN

		annotation SummarizationSetBy = User

	/// Candidat social-démocrate testé.
	column 'Candidat de gauche'
		dataType: string
		lineageTag: 5d6ed19d-2462-4422-bf89-0018de4e2413
		summarizeBy: none
		sourceColumn: CandidatGauche

		annotation SummarizationSetBy = User

	/// Configuration d'offre : quatre ou trois grands candidats face au RN.
	column Configuration
		dataType: string
		lineageTag: 899f46a8-63cc-44ea-a225-986261b8e048
		summarizeBy: none
		sortByColumn: OrdreConfig
		sourceColumn: Configuration

		annotation SummarizationSetBy = User

	column OrdreConfig
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a3651d58-a5d1-4eee-add1-70e4026c610c
		summarizeBy: none
		sourceColumn: OrdreConfig

		annotation SummarizationSetBy = User

	column Ordre
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a1105c48-faf3-4674-abb2-500c39d50e5e
		summarizeBy: none
		sourceColumn: Ordre

		annotation SummarizationSetBy = User

	partition Hypotheses = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "Hypotheses.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"Code", type text}, {"Hypothese", type text}, {"Intitule", type text}, {"Base", Int64.Type}, {"SansReponse", type number}, {"NbCandidats", Int64.Type}, {"FinalisteRN", type text}, {"CandidatGauche", type text}, {"Configuration", type text}, {"OrdreConfig", Int64.Type}, {"Ordre", Int64.Type}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
