/// Table de faits : un enregistrement par couple (hypothèse, candidat).
/// 84 lignes issues des pages 6 à 13 du rapport Ipsos.
table Intentions
	lineageTag: bb4d52cf-4d50-4d91-b59f-350da81b3834

	column Code
		dataType: string
		isHidden
		lineageTag: 2659af54-b8ae-4556-b13b-dd69af5ab95c
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = User

	column Candidat
		dataType: string
		isHidden
		lineageTag: 2498aadb-fb7f-40fd-bcf9-0c3ccecf8407
		summarizeBy: none
		sourceColumn: Candidat

		annotation SummarizationSetBy = User

	/// Intention de vote en % des suffrages exprimés.
	column Score
		dataType: double
		isHidden
		formatString: 0.0
		lineageTag: 5b0b8056-51bd-4d58-a337-9a821526b855
		summarizeBy: none
		sourceColumn: Score

		annotation SummarizationSetBy = User

	/// Demi-amplitude de l'intervalle de confiance à 95 %, en points.
	column Marge
		dataType: double
		isHidden
		formatString: 0.0
		lineageTag: 9b416fca-3520-485d-88d2-13ced6096b07
		summarizeBy: none
		sourceColumn: Marge

		annotation SummarizationSetBy = User

	partition Intentions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminDonnees & "Intentions.csv"), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"Code", type text}, {"Candidat", type text}, {"Score", type number}, {"Marge", type number}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
